export const FETCH_LOGIN = 'FETCH_LOGIN'
export const LOGIN = 'LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const LOGIN_ERROR = 'LOGIN_ERROR' 
export const GET_ACCOUNTS = 'GET_ACCOUNTS'
export const GET_ACCOUNTS_ERROR = 'GET_ACCOUNTS_ERROR'
